# Generated by Django 4.0.5 on 2022-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('url_hash', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048)),
                ('headers', models.BinaryField()),
                ('topic', models.CharField(max_length=200)),
                ('raw_content', models.BinaryField()),
            ],
        ),
    ]
